# Preface {.unnumbered}

Welcome to the online notes for **MAS3919 — Foundations of Machine Learning**.

This course is co-taught for MAS3919 and MAS8607.

## Outline of the Module {.unnumbered}

**Prequisities.** The formal prerequisites for this module are *either* MAS2901, MAS2909, and MAS2910, *or* MAS8600 and MAS8601.
(This module could still be accessible to a strong undergraduate student who did not take MAS2909 and was prepared to fill in the gaps where required.)

Sometimes we are asked if any other undergraduate modules might be complementary, and we would suggest MAS2806, MAS3702, MAS3928, MAS3929 and MSP3809.
Indeed, on one or two occasions we will refer to the technique of Lagrange multipliers from MSP3809, but this is for presentational completeness and will not be examined.

**Assessment.** This module is co-taught as both MAS3919 and MAS8607. Students taking MAS8607 can expect to be examined on at least one of the Advanced Topics, indicated with a [{{< fa star >}}]{.advanced title="MAS8607 content"}, while these are non-examinable for MAS3919. Non-examinable material for both cohorts is indicated with [{{< fa star >}}{{< fa star >}}]{.advanced title="Non-Examinable content"}. There will be five Exercise Sheets in total, with solutions presented at Problem Classes; these are worth 0% of your overall mark. There will be one summative assignment worth 20% of your overall mark, which will focus on coding in PyTorch. There will also be one mock written exam worth 0% during revision week. A written exam forms the remaining 80%.

**Learning Outcomes.** Distinct from most other modules, we will tend to emphasise understanding of *concepts* as opposed to detailed calculations, and your examination will test your ability both to recall these concepts and to give a coherent written explanation of their relevance in a given context.
After taking this module you should feel equipped with a broad knowledge of machine learning, enabling you to coherently communicate at a technical level in (e.g.) a job interview for a machine learning engineer post.
In addition, we will provide practical demonstrations of machine learning in PyTorch; you are expected to reproduce these as homework, as your summative assignment will focus on coding in PyTorch.

**Feedback.** These lecture notes are new for 2026 and are therefore bound to contain small errors; we would appreciate these being brought to our attention by emailing chris.oates@ncl.ac.uk or matthew.fisher@ncl.ac.uk. We also welcome general feedback.

---

```{=html}
<details>
      <summary> Show Module Schedule </summary>


<table class="schedule">
  <thead>
    <tr>
      <th scope="col">Teaching week</th>
      <th scope="col">Week<br>Beginning</th>
      <th scope="col">Topic</th>
      <th scope="col">Activities</th>
      <th scope="col">Assessment</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Date</td>
      <td>Week 1 Content </td>
      <td>Two in-person lectures</td>
      <td></td>
    </tr>

    <tr class="wk-alt">
      <th scope="row">2</th>
      <td>Date</td>
      <td>Week 2 Content </td>
      <td>Two in-person lectures</td>
      <td>Assignment</td>
    </tr>

    <tr>
      <th scope="row">3</th>
      <td>Date</td>
      <td>Week 3 Content</td>
      <td>Two in-person lectures</td>
      <td></td>
    </tr>

    <!-- Highlighted alternating week -->
    <tr class="wk-alt">
      <th scope="row"><strong>4</strong></th>
      <td>Date</td>
      <td>Content</td>
      <td>Two in-person lectures</td>
      <td>
        <p>Assignment due</p>
      </td>
    </tr>

    <tr>
      <th scope="row">5</th>
      <td>Date</td>
      <td>Content</td>
      <td>Two in-person lectures</td>
      <td></td>
    </tr>

    <!-- Highlighted alternating week -->
    <tr class="wk-alt">
      <th scope="row"><strong>6</strong></th>
      <td>Date</td>
      <td>Content</td>
      <td>Two in-person lectures</td>
      <td>
        <p>Assignment</p>
      </td>
    </tr>

    <!-- Enrichment banner -->
    <tr class="wk-enrich">
      <th colspan="5" scope="rowgroup"><strong>Enrichment Week</strong></th>
    </tr>

    <tr>
      <th scope="row">7</th>
      <td>Date</td>
      <td>Content</td>
      <td>Two in-person lectures</td>
      <td>
        <p>Assignemtn due</p>
      </td>
    </tr>

    <!-- Highlighted alternating week -->
    <tr class="wk-alt">
      <th scope="row"><strong>8</strong></th>
      <td>Date</td>
      <td><span>Content</span></td>
      <td>Two in-person lectures</td>
      <td>
        <p>Assignment</p>
      </td>
    </tr>

    <tr>
      <th scope="row">9</th>
      <td>Date</td>
      <td>Content</td>
      <td>Two in-person lectures</td>
      <td></td>
    </tr>

    <!-- Highlighted alternating week -->
    <tr class="wk-alt">
      <th scope="row"><strong>10</strong></th>
      <td>Date</td>
      <td>Content</td>
      <td>Two in-person lectures</td>
      <td>Assignment</td>
    </tr>

    <tr style="">
      <th scope="row"><strong>11</strong></th>
      <td>Date</td>
      <td>Revision Week</td>
      <td>Two in-person lectures</td>
      <td></td>
    </tr>

    <!-- Vacation banner -->
    <tr class="wk-vac">
      <th colspan="5" scope="rowgroup">Vacation</th>
    </tr>
  </tbody>
</table>

</details>


```

---
